### ISSUE TITLE
(FEATURE REQUEST NOT ISSUE) - Merge The "Owners" Section With Staff.

### ISSUE THREAD

**Issue by MelonicOverlord** [PedestriaMC-Network/PedestriapediaOfficial#11]
Feature Request:

Merge the owners section with the staff section. You can see an example of what I mean [here](https://i.imgur.com/AdXdwLm.png).

I would also like to request the removal of Ex-Staff as they aren't on the team anymore and shouldn't really be on a "pedestal" so to speak, if you know what I mean.

**Comment by Lukas-Batema** [comment]
Dear @MelonicOverlord,
Thank you for the input. I will be removing the ex-staff section, and moving the owners to the staff tab. That seems like a good thing to be done. I will keep this issue open for now, until I update it! Thanks once again!

Best Wishes,
Lukas Batema

**Comment by Lukas-Batema** [comment]
Dear @MelonicOverlord,
This has been fixed in the [latest commit](https://github.com/PedestriaMC-Network/PedestriapediaOfficial/commit/997ba3b70de5875dd5532b24d971d78707d28b9a)! If you find anything else, just let us know! Thanks for your input!
