### ISSUE TITLE
Remove The "Enter Text Here" Boxes

### ISSUE THREAD

**Issue by MelonicOverlord** [PedestriaMC-Network/PedestriapediaOfficial#12]
There are "Enter Text Here" boxes on all of the pages, they cannot be typed in and are unnecssecary.

**Comment by Lukas-Batema** [comment]
Dear @MelonicOverlord,
Those are currently placeholders for the footer, which will have the same links as on the [main site](https://www.pedestriamc.com/). I am the one who put those there, and I am aware of them. Thank you for the reminder!

Best Wishes,
Lukas Batema
