### ISSUE TITLE
this website need improvment

### ISSUE THREAD

**Issue by itsMeShon** [PedestriaMC-Network/PedestriapediaOfficial#23]
hey! this website needs improvement. the footer link is not visible. and some major bugs are there. I tried to fix that but it is not working. I saw you wrote the same code in that but your code is not affecting the link to make it to another color. I don't know why it is not working I tried to make the color and make it visible but it is not affecting the element. I added class and id and try but still, it is not working I am not understanding what happens to that. @Lukas-Batema just try to fix that.

**Comment by Lukas-Batema** [comment]
> hey! this website needs improvement. the footer link is not visible. and some major bugs are there. I tried to fix that but it is not working. I saw you wrote the same code in that but your code is not affecting the link to make it to another color. I don't know why it is not working I tried to make the color and make it visible but it is not affecting the element. I added class and id and try but still, it is not working I am not understanding what happens to that. @Lukas-Batema just try to fix that.

I will try to fix that; currently I do not have the time, and this was created before I knew JS, I will be adding JS soon, and fix this, but I am currently working on a PY project. Thanks fo your report, and I will keep this issue open!

**Comment by Lukas-Batema** [comment]
Ya know what, Imma fix it really quick. Thank you for attempting to fix it!

**Comment by Lukas-Batema** [comment]
I have tried fixing it, I do not know why it does not work...

**Comment by itsMeShon** [comment]
Yes it not working! Thats what i said something error occurs

**Comment by Lukas-Batema** [comment]
> Yes it not working! Thats what i said something error occurs @Lukas-Batema

I realise that. Could you please stop pinging me? I have figured out a fix, and have to apply it to the rest of the site.

**Comment by Lukas-Batema** [comment]
It is now fixed in my fork, will be updating this repo in the future, when I add more features. Closing this issue!

**Comment by itsMeShon** [comment]
K good!
